### ISSUE TITLE
Choosing the collection doesn't do anything

### ISSUE THREAD

**Issue by vwilson1** [KaFaiFai/anki_visualizer#1]
It creates a folder named ".dart_tool" , inside it another one called "sqflite_common_ffi" , inside it "databases" , and it has "anki_visualizer" with 176mb, Anki visualizer.db-shm with 32 kb, and anki_visualizer,db-wal with 0 kb of size

By "doesn't do anything" i mean that when i choose the collection.anki2 file, nothing appears, no selection, nothing.
however the text in the selection part changes to "please pick a collection.anki2 file again"

Tried multiple times

**Comment by CyrusCKF** [comment]
The text "please pick a collection.anki2 file again" suggests that the file you chose was not in the correct format.
I have attached an example database in `doc/anki_database_example/collection.anki2`. Can you try choosing this file and see if it works?

**Comment by vwilson1** [comment]
> The text "please pick a collection.anki2 file again" suggests that the file you chose was not in the correct format. I have attached an example database in `doc/anki_database_example/collection.anki2`. Can you try choosing this file and see if it works?

Yes, that did work with 1.0.0, my collection.anki2 however, doesn't.
Could it be due to the size? it is currently 180mb. I also own 20+ decks

With V.1.0.1 the example collection.anki2 didn't work however, worked with the 1.0.0. 1.0.1 doesn't create the .dart_tool folder too.

Windows 10 user

**Comment by CyrusCKF** [comment]
Hi, I am still trying to figure out the issue. I suspect that your collection.anki2 file may have a different schema than the one I have. So, I released version 1.0.2 that adds a logging function. When you run the program, it should store a log file in `Documents\Anki Visualizer\log.txt`.

Inputting a correct collection.anki2 file, like the one provided, will generate logs like the following in the last few lines:
```
[2024-04-30T10:31:26.520386] TRACE: Deleting existing database
[2024-04-30T10:31:26.522376] TRACE: Creating database copy
[2024-04-30T10:31:26.679047] DEBUG: All tables: android_metadata, cards, col, config, deck_config, decks, fields, graves, notes, notetypes, templates, revlog, sqlite_stat1, sqlite_stat4, tags
[2024-04-30T10:31:26.683046] INFO: Getting table "decks" ...
[2024-04-30T10:31:26.686046] INFO: Retrieved 19 decks
```

It would be helpful if you can retry it and upload your logs. Thank you

**Comment by vwilson1** [comment]
No need for, it went smoothly on this new update, good job keep it going

**Comment by vwilson1** [comment]
Started working as of the new update
