### ISSUE TITLE
"please pick a collection.anki2 file again"

### ISSUE THREAD

**Issue by bo-booo** [KaFaiFai/anki_visualizer#2]
I downloaded the zip file, unzipped it, opened anki_visaualizer.exe, clicked "pick your collection.anki2 file", selected my file, and the title showed up after a short loading animation. I have tried both my own anki2 file and the database example in the doc section with the same results. I'm using Windows 11 version 23H2. Any idea what went wrong?

**Comment by CyrusCKF** [comment]
Hi, I am still trying to figure out the issue. I suspect that your collection.anki2 file may have a different schema than the one I have. So, I released version 1.0.2 that adds a logging function. When you run the program, it should store a log file in `Documents\Anki Visualizer\log.txt`.

Inputting a correct collection.anki2 file, like the one provided, will generate logs like the following in the last few lines:
```
[2024-04-30T10:31:26.520386] TRACE: Deleting existing database
[2024-04-30T10:31:26.522376] TRACE: Creating database copy
[2024-04-30T10:31:26.679047] DEBUG: All tables: android_metadata, cards, col, config, deck_config, decks, fields, graves, notes, notetypes, templates, revlog, sqlite_stat1, sqlite_stat4, tags
[2024-04-30T10:31:26.683046] INFO: Getting table "decks" ...
[2024-04-30T10:31:26.686046] INFO: Retrieved 19 decks
```

It would be helpful if you can retry it and upload your logs. Thank you

**Comment by Maltesaa** [comment]
This problem seems to be fixed. I had the same problem with the prebuilt v1.01 exe, but when I built it myself I could import it no problem. The prebuilt v1.02 seems to work fine

**Comment by bo-booo** [comment]
HI, sorry for the late reply. The issue was indeed fixed for me as well in the new version. Thank you.
